#!/usr/bin/env bash
# Homebrew Packages

## stay current
brew update
brew upgrade

## core
# Add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
brew install moreutils
brew install findutils

## core
brew install vim --override-system-vi
brew install tmux
brew install ack
brew install ag
brew install wget --enable-iri
brew install unar
brew install tree
brew install bash
brew install git
brew install mercurial
brew install gnu-sed --default-names
brew install pv
brew install urlview
brew install xclip

## Web
brew brew install tidyp
brew brew install phantomjs
brew brew install slimerjs
brew brew install selenium-server-standalone
brew brew install chromedriver
brew brew install googlecl

## Media
brew install sox

## dev
brew install hub
brew install python
brew install node
brew install rest-shell
brew install resty
brew install spring-roo
brew install play
brew install jq
brew install drip
brew install sbt
brew install cheat
brew install swig
brew install ctags
#install jenkins
brew install go
brew install spring-loaded
brew install proguard
brew install lua
brew install lua51

## Data
brew install datamash
brew install protobuf
brew install protobuf-c

## Hardware
brew install picocom

## Virtualization
brew install docker
brew install juju
brew install fig
brew install awscli

## misc
brew install chrome-cli
brew install foremost
brew install imagemagick --with-webp
brew install pigz
brew install webkit2png
brew install zopfli
brew install heroku-toolbelt
brew install osxfuse
brew install httrack
brew install jmeter
brew install markdown
brew install htop-osx
brew install gpg

## sec / networking
brew install sqlmap
brew install nmap
brew install wireshark
brew install freerdp
brew install splint
brew install zmap
brew install libnet
brew install libnids
brew install denominator
brew install skipfish
brew install tor


## Make pbcopy play well with tmux
brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste

## brew
brew install brew-cask

# clean up cellar
brew cleanup

