# Homebrew Packages

## stay current
update
upgrade

## core
# Add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
install moreutils
install findutils

## core
install vim --override-system-vi
install tmux
install ack
install wget --enable-iri
install unar
install tree
install bash
install git
install mercurial
install gnu-sed --default-names
install pv
install urlview
install xclip

## Web
brew install tidyp
brew install phantomjs
brew install slimerjs
brew install selenium-server-standalone
brew install chromedriver

## Media
install sox

## dev
install hub
install python
install node
install rest-shell
install resty
install spring-roo
install play
install jq
install drip
install sbt
install cheat
install swig
install ctags
#install jenkins
install go
install spring-loaded

## Data
install datamash
install protobuf
install protobuf-c

## Hardware
install picocom

## Virtualization
install docker
install juju

## misc
install chrome-cli
install foremost
install imagemagick --with-webp
install pigz
install webkit2png
install zopfli
install heroku-toolbelt
install osxfuse
install httrack
install jmeter
install markdown
install htop-osx
install gpg

## sec / networking
install sqlmap
install nmap
install wireshark
install freerdp
install splint
install zmap

## brew
install brew-cask

# clean up cellar
cleanup
